---
sidebar: sidebar 
permalink: concept-onprem-ontap.html 
keywords: ontap, cluster, discover, manage, discovering, fas, aff, discover onprem, discover aff cluster, discover cluster, add cluster, active iq, digital wallet 
summary: BlueXP puede detectar los clústeres de ONTAP que se ejecutan en controladoras AFF/FAS y ONTAP Select. Añadir sistemas ONTAP en las instalaciones a BlueXP le permite gestionar todos sus activos de almacenamiento y datos desde una única interfaz. 
---
= Obtén más información sobre la gestión del clúster de ONTAP en las instalaciones en BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP puede detectar los clústeres de ONTAP que se ejecutan en controladoras AFF/FAS y ONTAP Select. Añadir sistemas ONTAP en las instalaciones a BlueXP le permite gestionar todos sus activos de almacenamiento y datos desde una única interfaz.



== Funciones

* Gestione volúmenes NFS y CIFS
* Lleve a cabo una gestión avanzada mediante System Manager de ONTAP
* Obtenga observabilidad de la salud y el rendimiento con el análisis y control de BlueXP
* Utiliza los servicios de BlueXP para replicar, hacer backups, escanear, clasificar y organizar los datos en niveles
* Consulta la información del estado de los contratos de hardware y software en la cartera digital de BlueXP




== Coste

Un coste puede estar asociado, pero depende de lo siguiente:

* Si implementa un conector para detectar y gestionar los clústeres.
+
Puede instalar el conector en la nube o en sus instalaciones.

* Tanto si usas servicios de BlueXP, como el backup y la recuperación de datos, la organización en niveles y la clasificación.

