---
sidebar: sidebar 
permalink: concept-aiq-digital-advisor.html 
keywords: concepts, active iq digital advisor, ontap 
summary: El asesor digital de BlueXP te permite optimizar las operaciones, la seguridad y el rendimiento de tus clústeres de ONTAP. 
---
= Optimiza los clústeres mediante el asesor digital de BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El asesor digital de BlueXP te permite optimizar las operaciones, la seguridad y el rendimiento de tus clústeres de ONTAP.



== Funciones

Puede ver el estado general de su sistema de almacenamiento, información de alto nivel sobre el estado del sistema, el inventario, la planificación, las renovaciones y la información valiosa a nivel de lista de seguimiento mediante el asesor digital de BlueXP.

* Analice y optimice el estado de sus sistemas de almacenamiento
* Obtenga información sobre todos los riesgos de sus sistemas de almacenamiento y las acciones para mitigar los riesgos
* Analice el rendimiento de sus dispositivos de almacenamiento viendo el formato gráfico de los datos de rendimiento
* Obtenga información detallada acerca de los sistemas que han superado el 90 % de la capacidad o que están cerca del 90 %
* Obtenga información acerca del hardware y el software que han caducado o que están cerca de caducar en los próximos 6 meses
* Actualice el software de su sistema de almacenamiento y actualice el firmware de ONTAP con Ansible




== Sistemas ONTAP compatibles

El asesor digital ofrece información para todos los sistemas de ONTAP en las instalaciones y los sistemas Cloud Volumes ONTAP asociados con su cuenta del sitio de soporte de NetApp (NSS).



== Más información

https://["Documentación del asesor digital"^]
