---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, system manager, unsupported features 
summary: Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto o cuya interoperabilidad con esta no es óptima. Revise estas limitaciones detenidamente. 
---
= Limitaciones conocidas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto o cuya interoperabilidad con esta no es óptima. Revise estas limitaciones detenidamente.



== Limitaciones relacionadas con los sistemas ASA R2

Después de detectar un sistema NetApp ASA R2 y abrir el entorno de trabajo, se le pasará directamente a System Manager.

No hay otras opciones de gestión disponibles con los sistemas ASA R2. No se puede utilizar la vista estándar y no se pueden habilitar los servicios de BlueXP.

https://docs.netapp.com/us-en/asa-r2/index.html["Obtenga más información sobre los sistemas R2 de ASA"^]



== Clústeres no compatibles

Los clústeres de ONTAP en las instalaciones que están configurados con autenticación SAML no son compatibles con BlueXP.



== Limitaciones de System Manager

BlueXP no admite las siguientes funciones de System Manager:

* Configuración del clúster
+
Después de establecer la dirección IP de gestión y configurar la contraseña de administrador en un clúster de ONTAP en las instalaciones, puede detectar el clúster en BlueXP.

* Control de acceso basado en roles (solo conector)
+
No se admite el control de acceso basado en roles de System Manager cuando se descubre y gestiona un clúster de ONTAP en las instalaciones mediante un conector. Se le pedirá que introduzca las credenciales de administrador durante el proceso de detección. Estas credenciales se utilizan para todas las acciones realizadas desde System Manager.

+
Con la opción de detección directa, se le pedirá que inicie sesión con sus credenciales de ONTAP cada vez que abra el entorno de trabajo.

* Activación de backup y recuperación de BlueXP (Cloud Backup)
+
La versión del clúster debe ser 9.13.1 para habilitar el backup y la recuperación de datos de BlueXP desde System Manager.

+
Si _not_ detectó un clúster mediante un Connector, no podrá usar System Manager (vista avanzada) para habilitar el backup y la recuperación. Sin embargo, puedes habilitar el backup y la recuperación en un clúster on-premises directamente desde BlueXP. https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["Aprenda cómo empezar"^]

* Actualizaciones bajo demanda
+
Las actualizaciones bajo demanda del firmware y del software no están disponibles si la versión del clúster es ONTAP 9.9.1 o una versión anterior.

+
Si tienes un conector, no puedes realizar actualizaciones desde tu equipo local, solo desde un servidor al que se puede acceder mediante BlueXP.

* Búsqueda global
* Configuración de la interfaz de usuario de

