---
sidebar: sidebar 
permalink: task-discovering-ontap.html 
keywords: ontap, cluster, discover, manage, discovering, fas, aff, discover onprem, discover aff cluster, discover cluster, add cluster, active iq, digital wallet 
summary: Descubra clústeres de ONTAP en las instalaciones desde BlueXP para que pueda empezar a gestionar volúmenes y a realizar una gestión avanzada con ONTAP System Manager, que está disponible en BlueXP. 
---
= Detectar clústeres de ONTAP en las instalaciones
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Descubre los clústeres de ONTAP on-premises de BlueXP para empezar a gestionar volúmenes y a realizar gestión avanzada mediante ONTAP System Manager, que está disponible en BlueXP.



== Opciones de detección y administración

BlueXP ofrece dos formas de detectar y gestionar sus clústeres de ONTAP en las instalaciones:

Detección a través de un conector:: Esta opción permite gestionar clústeres que ejecutan ONTAP 8.3 y versiones posteriores mediante las siguientes funciones:
+
--
* La vista estándar, que proporciona operaciones de volumen básicas
* La vista avanzada, que ofrece gestión a través de System Manager (compatible con ONTAP 9.10.0 y versiones posteriores).
* Integración con los servicios de BlueXP, que proporcionan replicación de datos, backup y recuperación, clasificación de datos y organización en niveles de los datos


Esta opción requiere un conector, que puede instalar en un proveedor de cloud o en sus instalaciones.

--
Descubrimiento directo:: Esta opción permite gestionar clústeres que ejecutan ONTAP 9.12.1 y versiones posteriores mediante System Manager. No hay otras opciones de administración disponibles. No se puede usar la vista estándar y no se pueden habilitar los servicios de datos.
+
--
Esta opción no requiere conector.

Cuando accede a System Manager en un clúster de ONTAP en las instalaciones con 9.12.1 o una versión posterior con conectividad al servicio BlueXP, se le solicitará que gestione el clúster directamente desde BlueXP. Si sigue este aviso, detecta el clúster en BlueXP mediante la opción de detección directa.

--


Una vez detectados, sus clusters estarán disponibles como un entorno de trabajo en BlueXP Canvas.

Si decide utilizar la otra opción de detección más adelante, deberá descubrir el clúster en las instalaciones como un entorno de trabajo independiente en el lienzo. A continuación, tiene la opción de eliminar el otro entorno de trabajo.



== Requisitos

Antes de descubrir el clúster de ONTAP en las instalaciones, asegúrese de haber cumplido los siguientes requisitos.



=== Requisitos generales

* Debería haber comenzado con BlueXP, que incluye el inicio de sesión y la configuración de una cuenta.
+
https://["Aprenda a comenzar con BlueXP"^]

* Necesita la dirección IP de administración del clúster y la contraseña de la cuenta de usuario administrador.
* BlueXP detecta los clústeres de ONTAP mediante HTTPS. Si utiliza políticas de firewall personalizadas, el clúster de ONTAP debe permitir el acceso HTTPS de entrada a través del puerto 443.
+
La política de firewall "mgmt" predeterminada permite el acceso HTTPS entrante desde todas las direcciones IP. Si ha modificado esta directiva predeterminada o si ha creado su propia directiva de firewall, debe asociar el protocolo HTTPS con esa directiva y habilitar el acceso desde el host de Connector.





=== Requisitos para la detección y administración del conector

* El clúster en las instalaciones debe ejecutar ONTAP 8.3 o una versión posterior.
* Un conector debe estar instalado en un proveedor de cloud o en sus instalaciones.
+
Si desea organizar en niveles datos inactivos en el cloud, debe revisar los requisitos del conector en función de dónde tenga pensado organizar los datos inactivos.

+
** https://["Más información sobre conectores"^]
** https://["Cambio entre conectores"^]
** https://["Más información sobre la organización en niveles de BlueXP"^]


* El host del conector debe permitir el acceso HTTPS de salida a través del puerto 443.
+
Si el conector está en la nube, el grupo de seguridad predefinido permite todas las comunicaciones salientes.





=== Requisitos para detección directa y gestión

* El clúster en las instalaciones debe ejecutar ONTAP 9.12.1 o una versión posterior.
* El clúster debe tener conectividad de entrada y salida al servicio BlueXP:
+
\https://cloudmanager.cloud.netapp.com/ontap-service/check-service-connection

* El equipo que está utilizando para acceder a la consola BlueXP debe tener una conexión de red al clúster ONTAP en las instalaciones, de forma similar a cómo proporcionaría conexiones a otros recursos de su red privada.




== Detectar clústeres

Descubre tus clusters de ONTAP en las instalaciones desde el lienzo en BlueXP. Al iniciar el proceso de detección, BlueXP detecta el clúster de la siguiente manera:

* Si tiene un conector activo que tiene una conexión a su clúster ONTAP, BlueXP utilizará ese conector para detectar y gestionar el clúster.
* Si no tiene un conector o si su conector no tiene una conexión con el clúster ONTAP, BlueXP utilizará automáticamente la opción de detección y administración directa.


.Pasos
. En el menú de navegación, selecciona *almacenamiento > Canvas*.
. En la página Canvas, haga clic en *Agregar entorno de trabajo* y seleccione *en las instalaciones*.
. Junto a On-local ONTAP, seleccione *Discover*.
. En la página _Discover_, introduzca la dirección IP de administración del clúster y la contraseña de la cuenta de usuario de administrador.
. Si está descubriendo el clúster directamente (sin conector), puede seleccionar *Guardar las credenciales*.
+
Si selecciona esta opción, no tendrá que volver a introducir las credenciales cada vez que abra el entorno de trabajo. Estas credenciales sólo están asociadas a su usuario de BlueXP. No se guardan para su uso por parte de nadie más de su cuenta.

. Seleccione *Discover*.


.Resultado
BlueXP detecta el clúster y lo agrega como un entorno de trabajo en el lienzo. Ahora puede empezar a gestionar el clúster.

* link:task-manage-ontap-direct.html["Conozca cómo se detectan directamente los clústeres"]
* link:task-manage-ontap-connector.html["Aprenda a gestionar clústeres detectados con un conector"]

